services:
  frontend:
    image: mpabon/wzleaguesfrontend
    build:
      context: ./src/frontend
    ports:
      - "8081:80"
    networks:
      - frontend
      - backend

  backend:
    image: mpabon/wzleagues
    build:
      context: ./src/playerService
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  frontend:
  backend: