name: CI to Docker Hub

on:
  push:
    branches: [ main ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:

          - name: Check Out Repo 
            uses: actions/checkout@v2

          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            
          - name: Build and push Docker images
            uses: docker/build-push-action@v1
            with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
              repository: ${{ secrets.DOCKER_HUB_USERNAME }}/wzleagues
              tags: latest
              build-args: KEY=${{ secrets.APP_ENCRYPTION_PASSWORD }}

          - name: Image digest
            run: echo ${{ steps.docker_build.outputs.digest }}
